#ifndef _ESPACE_EXAMPLE_ERROR_H
#define _ESPACE_EXAMPLE_ERROR_H

#include <espace/error.h>

ESPACE_ERRDEC(LIBA_E001);
ESPACE_ERRDEC(LIBA_E002);
ESPACE_ERRDEC(LIBA_E003);
ESPACE_ERRDEC(LIBA_E004);

#endif
