#ifndef _ESPACE_EXAMPLE_ERROR_H_
#define _ESPACE_EXAMPLE_ERROR_H_

#include <espace/error.h>

ESPACE_ERRDEC(LIBA_E001);               // declare ERROR
ESPACE_ERRDEC(LIBA_E002);
ESPACE_ERRDEC(LIBA_E003);
ESPACE_ERRDEC(LIBA_E004);

#endif
